#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Shiyi Chen

# Name of the author
author: Shiyi Chen

# Short bio or description (displayed in the header)
description: Shiyi's Personal Website

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: shiyi.chen@oneonta.edu





# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/ShiyiChen"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/


sass:
  style: :expanded # You might prefer to minify using :compressed
# nav
nav:
  - Home: /About/
  - CV: /about/
  - Research: /research/
  - Teaching: /teaching/


include: ['_pages']

paginate: 6
paginate_path: /page:num/


